parameters:
#    tuni_annonce.example.class: Tuni\AnnonceBundle\Example

services:
#    tuni_annonce.example:
#        class: %tuni_annonce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
