parameters:
#    tuni_front.example.class: Tuni\FrontBundle\Example

services:
#    tuni_front.example:
#        class: %tuni_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
